export const START_ENIGMA_SESSION = 'START_ENIGMA_SESSION'
export const START_ENIGMA_SESSION_SUCCESS = 'START_ENIGMA_SESSION_SUCCESS'
export const START_ENIGMA_SESSION_ERROR = 'START_ENIGMA_SESSION_ERROR'

export const startEnigmaSession = () => ({
  type: START_ENIGMA_SESSION,
})
